Basic QO-100 Dx Club API integration
magicbug/Cloudlog pull request #2035
Opened 2023-03-16 19:03 UTC by hugosilvaparagramanet

Adds a very basic integration to QO-100 Dx Club API, to allow users to automatically upload QSOs to the club's database.

Currently only works if "realtime upload" is set to "Yes" since there's no manual upload page.

The code is pretty much a copy&paste from the QRZ.com upload functionality.

2023-03-16 20:03 UTC, phl0 requested changes
Works ok for me. We should add some if's to the DB migrations scripts though.

2023-03-16 20:03 UTC, phl0 commented on application/migrations/115_add_webadif_api_export.php
I guess we should add some if's here to prevent failing on updates. See https://github.com/magicbug/Cloudlog/commit/5ac115ceee15782effb9147e709442696783f030

2023-03-17 08:55 UTC, phl0 reviewed
Not sure about the two columns in the base table. Normally there is only ADIF fields in there. Should we use user defined fields here @magicbug?

2023-03-17 08:55 UTC, phl0 commented on application/migrations/115_add_webadif_api_export.php
Yeah. This works as expected.

2023-03-17 14:08 UTC, magicbug commented
Yep keep them separate, also make sure the table is named something obvious :)

2023-03-17 15:35 UTC, phl0 commented
Test with separate table also successful here :)

2023-03-19 16:56 UTC, magicbug commented
Do we all agree this is OK to merge into dev branch for further testing before going public?

2023-03-19 19:29 UTC, phl0 commented
I have tested to the latest commit. Merge is ok from my point of view. But maybe we should ask @hugosilvaparagramanet if there is something left to add before :)

2023-03-20 13:42 UTC, hugosilvaparagramanet commented
@magicbug @phl0 I've just uploaded a new commit that fixes a duplication while "marking as uploded". 
From my tests the thing is ok, hopefully...

2023-03-20 14:53 UTC, merged