IMPORTANT Security fix: eQSL uses HTTP (not encrypted) communication
magicbug/Cloudlog pull request #2442
Opened 2023-08-27 13:00 UTC by petrkr

Since eqsl using HTTPS, there is no single reason (maybe just for debugging purposes) to use un-encrypted HTTP connection, especially if there are passwords in requests.

This PR replacing endpoints to HTTPS. What it does NOT do is update in database table "config", which was seeded from migration script 004. I am not familiar with this PHP database framework. So please add there change of

`
		$sql = "UPDATE config SET eqsl_download_url = 'http://www.eqsl.cc/qslcard/DownloadInBox.cfm' WHERE id=1";
`
to 
`
		$sql = "UPDATE config SET eqsl_download_url = 'https://www.eqsl.cc/qslcard/DownloadInBox.cfm' WHERE id=1";
`

I tested it on my server and communication is TLS based and works fine.

Before patch:
![image](https://github.com/magicbug/Cloudlog/assets/6428351/4afbc583-dd90-4dae-b01d-2a442ea0284d)

After patch
![image](https://github.com/magicbug/Cloudlog/assets/6428351/4f5a4ace-a2d8-46cd-bb14-c74ed8172e0f)

2023-08-27 13:07 UTC, magicbug commented
Yes would be nice if eQSL didn't want the password passed to it, it's worse that even they just store it in plain text so using a password just for the platform is important.

2023-08-27 13:07 UTC, magicbug requested changes
Overall looks fine but migration files needed.

2023-08-27 13:11 UTC, petrkr commented
Yes I know, but I do not know how to write migration files in this framework. So please if you can do...

I totally agree eQSL should use some API / REST with API keys, it do not need be OAuth2, simple API key will be enough, but users are not loud enough to push them to do that :(

Also problem is, old-school loggers/apps will NOT use those API, as nobody will put there such support I guess. But they could have it as two ways "old-insecure" and new secure.

2023-08-27 14:33 UTC, phl0 commented
> Yes I know, but I do not know how to write migration files in this framework. So please if you can do...

Look in application/migrations. There is various examples. Should not be too hard.

2023-08-27 15:15 UTC, petrkr commented
Well.. I will just stop doing my job and learn new framework :) I though someone help me with this as-well... Anyway, I just did some best effort without framework knowledge, I do not know if that is right way, how to do such job in this and I really do not know how to run migrations or how to test it. Or how to run downgrade (because I found there down function, so I suppose it is for downgrading db version).

2023-08-27 15:17 UTC, phl0 commented
Nah not needed. I will do that then.

2023-08-27 15:20 UTC, petrkr commented
I tried to do some, but can not test, because I am running master version and there is some one more migration between dev and master branch, so I can not test it on mine server unless I will set up development environment aswell

2023-08-29 07:27 UTC, AndreasK79 commented
Migration script tested working ok. No errors, and url was changed on up- and downgrade.

2023-08-29 10:49 UTC, phl0 commented
> @phl0 did u checked i I've done it right way? Thanks

Yepp. Just tested. Sorry for delay. I would remove the echo output on downgrade as this will most probably not happen to any user and if they would only see it once on reloading and then gone ...

![Screenshot from 2023-08-29 12-49-04](https://github.com/magicbug/Cloudlog/assets/7112907/c3b2aefe-6967-4df9-8154-da3649fa7704)

2023-08-29 11:29 UTC, phl0 commented
Just talked to @AndreasK79 about this and we came to the conclusion that best would be to just leave downgrade empty. This does not even switch back to insecure HTTP at all. And would not require such notice.

2023-08-29 21:31 UTC, magicbug commented
> Yepp. Just tested. Sorry for delay. I would remove the echo output on downgrade as this will most probably not happen to any user and if they would only see it once on reloading and then gone ...

Yep agreed @phl0

2023-08-29 21:35 UTC, petrkr commented
> > Yepp. Just tested. Sorry for delay. I would remove the echo output on downgrade as this will most probably not happen to any user and if they would only see it once on reloading and then gone ...
> 
> Yep agreed @phl0

Check latest PR

2023-08-30 06:50 UTC, merged