Add user-selectable 'Name' column
magicbug/Cloudlog pull request #2734
Opened 2023-11-26 17:51 UTC by DJ3CE

This commit adds a user selectable 'Name' column to the 4 (5) user-configurable columns. There had been an 'operator'-option, which shows the operator name of the "own station", so with this change, there's also a way to show the remote operators name.

I put the option behind the 'operator'-entry and reused the 'general_word_name'-localization field.

Feedback appreciated :).

2023-11-26 19:09 UTC, HB9HIL requested changes
option should be also added in `application/views/user/create.php`

2023-11-26 19:12 UTC, DJ3CE commented
Thank you for the hint. Found it, added it :).

2023-11-26 19:13 UTC, HB9HIL commented
Yeah my bad. said create.php but it is obviously add.php 😆

2023-11-26 19:14 UTC, HB9HIL approved these changes
Looks good to me. Works as expected.

2023-11-27 05:59 UTC, int2001 approved these changes
Works as expected. Nice one!

2023-11-27 07:25 UTC, phl0 approved these changes
Tested and works (both for editing a user and creating a new user).

2023-11-27 07:56 UTC, merged